-- Draw a custom dashboard inside the firmware-managed border.
local s = rf.status()
rf.gui_begin("LUA RF DASH")
rf.gui_text(4, 4, string.format("PEAK CH %d", s.peak_channel), "accent")
rf.gui_text(100, 4, string.format("%d%%", s.peak_level), "yellow")
rf.gui_rect(4, 18, 144, 14, "gray", false)
rf.gui_rect(6, 20, math.floor(140 * s.peak_level / 100), 10, "green", true)
rf.gui_line(4, 39, 147, 39, "gray")
rf.gui_text(4, 45, "RADIOS", "gray")
rf.gui_text(52, 45, tostring(s.radios), s.radios > 0 and "green" or "red")
rf.gui_text(4, 57, "CONF", "gray")
rf.gui_text(52, 57, tostring(s.confidence) .. "%", "white")
rf.gui_circle(132, 57, 8, s.logging and "red" or "gray", s.logging)
rf.gui_text(4, 70, "A=RERUN  B=LIST", "accent")
