#!/usr/bin/env python3
"""Generate a LuaLS/EmmyLua library stub for the firmware's ``rf`` API.

Names, signatures, types, defaults, and descriptions are all read from the
machine-readable metadata block in LuaEngine.cpp. Generation fails when the
metadata and actual C API registrations get out of sync.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "src/services/LuaEngine.cpp"
DEFAULT_OUTPUT = ROOT / "tools/generated/rfsuite.lua"


METADATA_PATTERN = re.compile(
    r"/\* LUA_LIBRARY_METADATA\s*(\{.*?\})\s*LUA_LIBRARY_METADATA_END \*/",
    re.DOTALL,
)


def registered_functions(source: str) -> set[str]:
    pattern = re.compile(
        r"lua_pushcfunction\(state,\s*\w+\);\s*"
        r'lua_setfield\(state,\s*-2,\s*"([a-z0-9_]+)"\);'
    )
    return set(pattern.findall(source))


def read_metadata(source: str) -> dict:
    match = METADATA_PATTERN.search(source)
    if not match:
        raise ValueError("LUA_LIBRARY_METADATA block not found")
    metadata = json.loads(match.group(1))
    if not isinstance(metadata, dict):
        raise ValueError("Lua API metadata must be a JSON object")
    annotations = metadata.get("annotations")
    functions = metadata.get("functions")
    if not isinstance(annotations, list) or not all(isinstance(line, str) for line in annotations):
        raise ValueError("Lua API annotations must be an array of strings")
    if not isinstance(functions, list) or not functions:
        raise ValueError("Lua API functions must be a non-empty array")
    names = [function.get("name") for function in functions]
    if any(not isinstance(name, str) or not name for name in names):
        raise ValueError("every Lua API metadata entry needs a name")
    if len(names) != len(set(names)):
        raise ValueError("duplicate Lua API metadata name")
    for function in functions:
        if not isinstance(function.get("description"), str):
            raise ValueError(f"Lua API metadata {function['name']} needs a description")
        for key in ("params", "returns"):
            values = function.get(key, [])
            if not isinstance(values, list) or not all(isinstance(value, dict) for value in values):
                raise ValueError(f"Lua API metadata {function['name']}.{key} must be an array")
    return metadata


def validate(source: str, functions: list[dict]) -> None:
    actual = registered_functions(source)
    documented = {function["name"] for function in functions}
    missing = sorted(actual - documented)
    stale = sorted(documented - actual)
    if missing or stale:
        details = []
        if missing:
            details.append("missing metadata: " + ", ".join(missing))
        if stale:
            details.append("not registered by firmware: " + ", ".join(stale))
        raise ValueError("Lua API metadata is out of sync (" + "; ".join(details) + ")")


def generate(metadata: dict) -> str:
    lines = [
        "---@meta RFSuite",
        "-- Generated by tools/generate_lua_library.py; do not edit manually.",
        "-- This file is for editor completion/type checking and is not copied to the SD card.",
        "",
    ]
    lines.extend(metadata["annotations"])
    lines.extend(("", "---@class RfApi", "---@type RfApi", "rf = {}"))
    functions = metadata["functions"]
    for function in functions:
        lines.extend(("", "---" + function["description"]))
        for parameter in function.get("params", []):
            name, lua_type = parameter["name"], parameter["type"]
            default = parameter.get("default")
            optional = "?" if "default" in parameter else ""
            suffix = f" Default: `{default}`." if "default" in parameter else ""
            lines.append(f"---@param {name}{optional} {lua_type}{suffix}")
        for returned in function.get("returns", []):
            lua_type, description = returned["type"], returned.get("description")
            suffix = f" {description}" if description else ""
            lines.append(f"---@return {lua_type}{suffix}")
        arguments = ", ".join(parameter["name"] for parameter in function.get("params", []))
        lines.append(f"function rf.{function['name']}({arguments}) end")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="path to LuaEngine.cpp")
    parser.add_argument("--output", "-o", type=Path, default=DEFAULT_OUTPUT, help="generated Lua library path")
    parser.add_argument("--check", action="store_true", help="fail if the output is absent or stale")
    args = parser.parse_args()

    try:
        source = args.source.read_text(encoding="utf-8")
        metadata = read_metadata(source)
        validate(source, metadata["functions"])
    except (OSError, ValueError, json.JSONDecodeError) as error:
        parser.error(str(error))

    content = generate(metadata)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != content:
            diff = difflib.unified_diff(
                current.splitlines(), content.splitlines(),
                fromfile=str(args.output), tofile="generated", lineterm=""
            )
            print("\n".join(diff), file=sys.stderr)
            print("Lua library is stale; run tools/generate_lua_library.py", file=sys.stderr)
            return 1
        print(f"Lua library is up to date: {args.output}")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(content, encoding="utf-8")
    print(f"Generated {args.output} ({len(metadata['functions'])} functions)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
